"""empty message

Revision ID: 7018f945ddd9
Revises: 
Create Date: 2019-06-22 09:09:09.389228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7018f945ddd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blog_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('imgurl', sa.String(length=250), nullable=True),
    sa.Column('blog_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_type'], ['blog_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('blog_type')
    # ### end Alembic commands ###
