"""empty message

Revision ID: f8fd210ebc15
Revises: 7018f945ddd9
Create Date: 2019-06-22 10:51:27.879329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8fd210ebc15'
down_revision = '7018f945ddd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_type', sa.Column('typename', sa.String(length=20), nullable=True))
    op.drop_column('blog_type', 'blog_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_type', sa.Column('blog_type', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('blog_type', 'typename')
    # ### end Alembic commands ###
